---
title: "4.1_Fitted_affected_rate_positive_direction"
author: "Jory Curry"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    code_folding: show
    df_print: paged
    toc: true
    toc_depth: 5
    toc_float: true
    theme: readable
params:
  direction: "pos"
  sample_size: 1000
  n_dose_groups: 6
  endpoint: "Affected.Rate"
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries, include=FALSE}
library(Rcurvep)
library(tidyverse)
library(future)
library(future.apply)
library(furrr)
library(kableExtra)
library(tcpl)
library(grid)
library(gridExtra)
source("Functions/RCurveP_Data_Wrangling_Functions.R")
```

```{r import_data, include=FALSE, message=FALSE, warning=FALSE}
ar_dat <- read_csv(file = "Data/apicaldata_ol_rm_and_Lethal_Dose-lowest_dose_removed.csv")

metaData <- read.csv(file = "Data/MetaData.csv", skip = 1) #Import the Meta Data that includes information about the data in the folders
#CAS is the Chemical Abstract Service, MOA is the Mode of Action. This table includes useful information about the exposure concentrations for each chemical dose in mg/L. We'll use this later to create our final data frame
doseData <- metaData %>%
  dplyr::select(Chemical, Dose_1:Dose_6) %>%
  rename(Control = Dose_6) %>%
  gather(key = Dose, value = "Dose_mg_L", Dose_1:Control)

lowest_dose_treatment_group <- doseData %>%
  filter(Dose != "Control") %>%
  dplyr::summarize(lowest_dose_treatment_group = min(Dose_mg_L))
lowest_dose_treatment_group <- lowest_dose_treatment_group[1,][[1]]

ss <- params$sample_size
dir <- params$direction
number_of_dose_groups_per_chem <- params$n_dose_groups # Set this to the number of dose groups you have (including control)

bmr_thresh <- readRDS("Data/positive_direction_bmr.R")
input_tib <- readRDS("Data/positive_direction_bmr_tibble.R")
```

```{r prep_data_for_rCurveP, echo=TRUE}
ar_dat <- ar_dat %>%
  mutate(endpoint = "Affected.Rate") %>%
  mutate(resp = get(params$endpoint)) %>%
  rename(chemical = Chemical) %>%
  mutate(Dose..mg.L. = Dose..mg.L./lowest_dose_treatment_group[[1]]) %>%
  mutate(conc = log10(Dose..mg.L.)) %>%
  group_by(chemical, endpoint) %>%
  mutate(control_conc = max(conc)-(number_of_dose_groups_per_chem-1)) %>% #making sure there are no infinite values for concentrations. Controls are made to be 1 dose group down from the lowest concentration
  mutate(conc = if_else(condition = conc == -Inf, true = control_conc, false = conc)) %>%
  dplyr::select(endpoint, chemical, conc, resp)
```

```{r CurveP_calc, echo=TRUE, message=FALSE, warning=FALSE}
#calculate the BMD step 1
#Run Hill model and linear model fit
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
#positive direction
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
fitted_expr <- expression(value(future({
  run_fit(
    create_dataset(input_tib$data[[1]]),
    modls = c("hill", "cnst"),
    keep_sets = c("fit_set", "resp_set"),
    n_samples = ss,
    #hill_pdir = 1,
    #Note: Hill dir introduced NAs so changing
    seed = 42069
  )
}, seed = 42069)))

fitted <- eval(fitted_expr)

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
```

```{r summarise_rcurveP_results, echo=TRUE}
#calculate the BMD step 2
#Wrangling
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
# Rcurvep has a problem where if the hill model can't be fitted using a specific direction for any of the simulated responses, it just sets them all to NA. This is an issue because it makes plotting the failed models impossible. SO going to resample the responses for those chemicals that get flagged as NA so i can re-model them myself for images even though they go in the incorrect direction.
#Index what chemicals are NAs only
test <- fitted$result$resp_set %>%
  group_by(chemical) %>%
  summarise(is_NaN = mean(resp, na.rm=TRUE))
  
NaNs <- as.vector(test[is.nan(test$is_NaN),][,1])

filter_1 <- fitted$result$resp_set %>%
  group_by(chemical) %>%
  filter(!chemical %in% NaNs[[1]])

filter_2 <- create_dataset(input_tib$data[[1]], n_samples = params$sample_size) %>%
  group_by(chemical) %>%
  filter(chemical %in% NaNs[[1]]) %>%
  mutate(direction = NA,
         fitted_resp = NA,
         sample_id = as.character(sample_id)) %>%
  mutate(resp = if_else(condition = resp < (-bmr_thresh), true = 0, false = resp))

replaced_NAs <- rbind(filter_1, filter_2)

fitted$result$resp_set <- replaced_NAs
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
fitted_output <-
  summarize_fit_output(d = fitted, thr_resp = bmr_thresh, ci_level = 0.95)

fitted_output_summary <-
  summarise_fitted_results(
    resp_set = fitted_output$result$resp_set,
    act_set = fitted_output$result$act_set,
    fit_set = fitted_output$result$fit_set,
    act_summary = fitted_output$act_summary,
    reject_hit_conf_under = 0.01
  )
# Weird bug in the RCurveP_Data_Wrangling_Functions.R source 'summarise_fitted_results' function where the hit_confidence vriable needs to be divided by an addional 100 ??? - 2022/10/27

fitted_hits <- fitted_output_summary %>%
  filter(hit == 1)

confident_fitted_hits <- confident_hits(summary_dat = fitted_hits, reject_hit_conf_under = 0.01)
#If error message says 'out of bounds', there are likely no confident hits at all

bmds_fitted <- fitted_output_summary %>%
  group_by(chemical) %>%
  summarise(
    median_POD = unique(median_POD),
    POD_med = unique(POD_med),
    cil_POD = unique(cil_POD),
    mean_POD = unique(mean_POD),
    ciu_POD = unique(ciu_POD),
    hit_confidence = unique(hit_confidence),
    lowest_conc = unique(lowest_conc),
    highest_conc = unique(highest_conc)
  )


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#

#Data Wrangling for nice labels
fitted_output_summary <- fitted_output_summary %>%
  group_by(chemical) %>%
  mutate(x_label_num = if_else(condition = conc == lowest_conc, true = 0, false = (10^conc)*lowest_dose_treatment_group)) %>%
  mutate(x_label = factor(x_label_num, levels = c(0, lowest_dose_treatment_group, lowest_dose_treatment_group*10, lowest_dose_treatment_group*100, lowest_dose_treatment_group*1000, lowest_dose_treatment_group*10000, lowest_dose_treatment_group*100000, lowest_dose_treatment_group*1000000, lowest_dose_treatment_group*10000000, lowest_dose_treatment_group*100000000, lowest_dose_treatment_group*1000000000, lowest_dose_treatment_group*10000000000), ordered = TRUE))

fitted_hits <- fitted_hits %>%
  group_by(chemical) %>%
  mutate(x_label_num = if_else(condition = conc == lowest_conc, true = 0, false = (10^conc)*lowest_dose_treatment_group)) %>%
  mutate(x_label = factor(x_label_num, levels = c(0, lowest_dose_treatment_group, lowest_dose_treatment_group*10, lowest_dose_treatment_group*100, lowest_dose_treatment_group*1000, lowest_dose_treatment_group*10000, lowest_dose_treatment_group*100000, lowest_dose_treatment_group*1000000, lowest_dose_treatment_group*10000000, lowest_dose_treatment_group*100000000, lowest_dose_treatment_group*1000000000, lowest_dose_treatment_group*10000000000), ordered = TRUE))
```

```{r table_the_results, echo=TRUE}
#Table the results
temp <- list(bmds_fitted)
names(temp) <- c(paste0("fitted_affected_rate_", dir, "_dir"))
all_summarized_bmd_dat <- plyr::ldply(temp)
all_summarized_bmd_dat <- all_summarized_bmd_dat %>%
  dplyr::arrange(chemical)

all_summarized_bmd_dat %>%
  mutate(lowest_conc = lowest_conc + 1) %>%
  mutate(
    lowest_conc = (10 ^ lowest_conc)*lowest_dose_treatment_group,
    highest_conc = sprintf((10 ^ highest_conc)*lowest_dose_treatment_group, fmt = '%.7f'),
    cil_POD = (10 ^ cil_POD)*lowest_dose_treatment_group,
    POD_med = (10 ^ POD_med)*lowest_dose_treatment_group,
    ciu_POD = (10 ^ ciu_POD)*lowest_dose_treatment_group,
    median_POD = (10 ^ median_POD)*lowest_dose_treatment_group,
    mean_POD = (10 ^ mean_POD)*lowest_dose_treatment_group
  ) %>%
  mutate(POD_med = if_else(is.na(POD_med), true = median_POD, false = POD_med)) %>%
  dplyr::select(
    chemical,
    .id,
    lowest_conc,
    highest_conc,
    cil_POD,
    POD_med,
    ciu_POD,
    hit_confidence
  ) %>%
  kable(
    col.names = c(
      "Chemical",
      "endpoint",
      "Low Dose (mg/L)",
      "High Dose (mg/L)",
      "BMD - low confidence interval (0.05)",
      "BMD",
      "BMD - high confidence interval (0.95)",
      "Hit Confidence"
    ),
    caption = "Table 9. Summary of all the benchmark doses (BMDs) of every chemical"
  ) %>%
  kable_styling() %>%
  row_spec(
    which(
      all_summarized_bmd_dat$median_POD < all_summarized_bmd_dat$highest_conc
    ),
    bold = TRUE,
    background = "gray"
  ) %>%
  scroll_box()
```

```{r 2.save_the_resutls, include=FALSE}
#Save the data
data <- all_summarized_bmd_dat %>%
  mutate(lowest_conc = lowest_conc + 1) %>%
  mutate(
    lowest_conc = (10 ^ lowest_conc)*lowest_dose_treatment_group,
    highest_conc = sprintf((10 ^ highest_conc)*lowest_dose_treatment_group, fmt = '%.7f'),
    cil_POD = (10 ^ cil_POD)*lowest_dose_treatment_group,
    POD_med = (10 ^ POD_med)*lowest_dose_treatment_group,
    ciu_POD = (10 ^ ciu_POD)*lowest_dose_treatment_group,
    median_POD = (10 ^ median_POD)*lowest_dose_treatment_group,
    mean_POD = (10 ^ mean_POD)*lowest_dose_treatment_group
  ) %>%
  mutate(POD_med = if_else(is.na(POD_med), true = median_POD, false = POD_med))

write_csv(x = data, file = paste0("Output/", "BMDs/", "fitted_", "affected_rate_", dir, "_", "BMDs_", ss, "_samples.csv"))
saveRDS(fitted_output_summary, file = paste0("Data/fitted_output_summary_", ss, "_samples.RDS"))
saveRDS(bmds_fitted, file = paste0("Data/fitted_bmds_", ss, "_samples.RDS"))
```